function savePulseSequence(pulse_sequence,soft_crushers,isInKspace,...
    N_pulse,info,gamma,dt,filename)

save(filename,'pulse_sequence','soft_crushers','isInKspace',...
    'N_pulse','info','gamma','dt')