function [sessionData] = connectRedis(sessionData)

%% Read connection-details for connecting to redis
if isfield(sessionData.instanceData,'simulatorinstance') && ...
        strcmp(sessionData.instanceData.simulatorinstance,'production')
    redisConnDetails = eduTool.setup.readRedisConnDetails(...
        'inputs/redisJsonStandaloneProduction.txt');
else
    redisConnDetails = eduTool.setup.readRedisConnDetails(...
        'inputs/redisJsonStandalone.txt');
end

sessionData.redis.R = tools.redis.redisEstablishConnection(...
    redisConnDetails.address,redisConnDetails.port,...
    str2num(redisConnDetails.inputBufferSize),...
    str2num(redisConnDetails.outputBufferSize));