function notifyAdminForErrors(conn,errorMessage,instance_id)

try
    curs2 = exec(conn, ...
        ['INSERT INTO edt_tool_local.backend_log(id, instance_id,',...
        'backendErrorLabel,backendErrorText) VALUES (NULL, ''',instance_id,''',''Error'',''',...
        strrep(errorMessage,'''',''),''')']);
    if ~isempty(curs2.Message)
        error('Unable to write error message in backend log. Send the default error message.')
    end
catch ME2
    curs3 = exec(conn, ...
        ['INSERT INTO edt_tool_local.backend_log(id, instance_id,',...
        'backendErrorLabel,backendErrorText) VALUES (NULL, ''',instance_id,''',''Error'',''',...
        'Not possible to catch the error due to special characters in the error message'')']);
end