function errorMessage = printErrorMessage(sessionData,ME)

timeStamp = datestr(now,'yyyy-mm-dd HH:MM:SS');
errorMessage = sprintf(['%s - User (%d) - ',...
    '(On Booting) Error in function %s() at line %d.',...
    '\n\nError Message:\n%s'], ...
    timeStamp,sessionData.userID,...
    ME.stack(1).name,ME.stack(1).line,ME.message);
fprintf(1, '\n%s\n', errorMessage);